version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports: ["9200:9200"]
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: ["5601:5601"]
    depends_on: ["elasticsearch"]
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.14.3
    command: ["apm-server","-e","-E","output.elasticsearch.hosts=[http://elasticsearch:9200]"]
    ports: ["8200:8200"]
    depends_on: ["elasticsearch"]
