name: trivy-scan
on: [push, pull_request]
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t api:ci apps/api
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: api:ci
          severity: HIGH,CRITICAL
          exit-code: '1'
